export const SHOW_LOADING = 'SHOW_LOADING';
export const GET_ANSWERS = 'GET_ANSWERS';
export const GET_ANSWERS_VALIDATED = 'GET_ANSWERS_VALIDATED';
export const GET_ANSWERS_NO_VALIDATED = 'GET_ANSWERS_NO_VALIDATED';
export const ADD_ANSWER = 'ADD_ANSWER';
